In [1]:
# pip install nltk

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 4.8 MB/s eta 0:00:00a 0:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 288.9/288.9 kB 1.2 MB/s eta 0:00:00a 0:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 96.6/96.6 kB 2.1 MB/s eta 0:00:00a 0:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.1/77.1 kB 2.0 MB/s eta 0:00:00

[notice] A new release of pip is available: 23.0.1 -> 23.1.2
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [31]:
from nltk.tokenize import word_tokenize
from nltk.tokenize import WordPunctTokenizer
import nltk

In [ ]:
nltk.download()

In [ ]:
# ssl 에러 발생 , nltk_data 경로 식별이 안될때
# import nltk
# import ssl

# try:
#     _create_unverified_https_context = ssl._create_unverified_context
# except AttributeError:
#     pass
# else:
#     ssl._create_default_https_context = _create_unverified_https_context

# nltk.download()

showing info https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/index.xml


In [3]:
s = "Don't be fooled by the dark sounding name, Mr. Jone's Orphanage is as cheery as cheery goes for a pastry shop."

In [33]:
from nltk.stem import WordNetLemmatizer
import nltk

In [32]:
lemmatizer = WordNetLemmatizer()

In [34]:
words = ['policy', 'doing', 'organization', 'have', 'going', 'love', 'lives', 'fly', 'dies', 'watched', 'has', 'starting']


In [35]:
[lemmatizer.lemmatize(word) for word in words]

['policy',
 'doing',
 'organization',
 'have',
 'going',
 'love',
 'life',
 'fly',
 'dy',
 'watched',
 'ha',
 'starting']

In [43]:
a = lemmatizer.lemmatize('dies',pos='v')

In [44]:
a

'die'

In [45]:
# 불용어(stopword) : 의미 분석에 도움안되는 것들
# nltk.corpus 에서 제공해줌, 그냥 i, me , my 같은 언어 리스트임
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

In [72]:
stop_list = stopwords.words('english')[:10]
example = "most important is doing ourselves, not you or only me my self"
stop_list

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're"]

In [73]:
result = [i for i in word_tokenize(example) if i not in stop_list]

In [74]:
print(result.__len__(), word_tokenize(example).__len__())

9 13


In [79]:
# Open Korean Text
from konlpy.tag import Okt

In [80]:
okt = Okt()

In [97]:
example = "고기를 아무렇게나 구우려고 하면 안 돼. 고기라고 다 같은 게 아니거든. 예컨대 삼겹살을 구울 때는 중요한 게 있지."
stop_exam = "를 아무렇게나 구 우려 고 안 돼 같은 게 구울 때 는"

In [99]:
stop_words = set(stop_exam.split(' '))
word_tokens = word_tokenize(example)

In [104]:
result = [word for word in word_tokens if word not in stop_words]
result

['고기를',
 '구우려고',
 '하면',
 '.',
 '고기라고',
 '다',
 '아니거든',
 '.',
 '예컨대',
 '삼겹살을',
 '때는',
 '중요한',
 '있지',
 '.']

In [106]:
from nltk.tokenize import sent_tokenize, word_tokenize
from nltk.corpus import stopwords

In [107]:
raw_text = "A barber is a person. a barber is good person. a barber is huge person. he Knew A Secret! The Secret He Kept is huge secret. Huge secret. His barber kept his word. a barber kept his word. His barber kept his secret. But keeping and keeping such a huge secret to himself was driving the barber crazy. the barber went up a huge mountain."

In [127]:
sentences = sent_tokenize(raw_text)
vocab = {}
preprocessed_sentences = []
stop_words = set(stopwords.words('english')) #영어 불용어


In [128]:
preprocessed_sentences = []

In [131]:
# 문장별 전처리
# 1) 소문자 혹은 대문자로 처리
# 2) stopwords 인지 판단
# 3) 길이가 2 이상인 것만 리스트에 넣고, 보캐브러리 딕셔너리에 할당해줌
for sentence in sentences:
    # 단어 토큰화
    tokenized_sentence = word_tokenize(sentence)
    result = []

    for word in tokenized_sentence:
        word = word.lower()
        if word not in stop_words:
            if len(word) > 2 :
                result.append(word)
                if word not in vocab:
                    vocab[word] = 1
                else:
                    vocab[word] += 1
    preprocessed_sentences.append(result)

In [133]:
preprocessed_sentences.__len__()

11

In [143]:
print(f'단어 집학:', vocab)

단어 집학: {'barber': 17, 'person': 7, 'good': 2, 'huge': 10, 'knew': 2, 'secret': 12, 'kept': 8, 'word': 4, 'keeping': 4, 'driving': 2, 'crazy': 2, 'went': 2, 'mountain': 2}


In [145]:
vocab_sorted = sorted(vocab.items(), key = lambda x:-x[1]) #빈도수 정렬 리스트, 엘리먼트는 튜플
vocab_sorted

[('barber', 17),
 ('secret', 12),
 ('huge', 10),
 ('kept', 8),
 ('person', 7),
 ('word', 4),
 ('keeping', 4),
 ('good', 2),
 ('knew', 2),
 ('driving', 2),
 ('crazy', 2),
 ('went', 2),
 ('mountain', 2)]

In [160]:
# 빈도수 높은 순서대로 단어를 정렬
# 빈도 상위 5위만 ,
freq_vocab = { word[0]:i for i,word in enumerate(vocab_sorted, start=1) if i < 6}

In [161]:
freq_vocab

{'barber': 1, 'secret': 2, 'huge': 3, 'kept': 4, 'person': 5}

In [164]:
# OOV : Out-Of-Vocabulary , 단어 집합에 없는 단어, index+1 로 딕셔너시 생성
freq_vocab['OOV'] = len(freq_vocab) + 1
freq_vocab

{'barber': 1, 'secret': 2, 'huge': 3, 'kept': 4, 'person': 5, 'OOV': 7}

In [172]:
encoded_sentences = [[freq_vocab[j] if j in freq_vocab else 6 for j in i]for i in preprocessed_sentences]
encoded_sentences

[[1, 5],
 [1, 6, 5],
 [1, 3, 5],
 [6, 2],
 [2, 4, 3, 2],
 [3, 2],
 [1, 4, 6],
 [1, 4, 6],
 [1, 4, 2],
 [6, 6, 3, 2, 6, 1, 6],
 [1, 6, 3, 6]]

In [177]:
# Counter 모듈도 사용가능
from collections import Counter
vocab = Counter(sum(preprocessed_sentences,[])).most_common(5)
vocab

[('barber', 8), ('secret', 6), ('huge', 5), ('kept', 4), ('person', 3)]

In [178]:
from nltk import FreqDist
import numpy as np
vocab = FreqDist(np.hstack(preprocessed_sentences))

In [182]:
vocab

FreqDist({'barber': 8, 'secret': 6, 'huge': 5, 'kept': 4, 'person': 3, 'word': 2, 'keeping': 2, 'good': 1, 'knew': 1, 'driving': 1, ...})

# 패딩 기법


In [187]:
# 문장들 중 max_length 로 패딩 해줘야함
max_len  = max(len(i) for i in encoded_sentences)
max_len

7

In [195]:
# keras pad_sequences 모듈 쓰면 편한
from tensorflow.keras.preprocessing.sequence import pad_sequences

padded = pad_sequences(encoded_sentences,padding='post') # padding='pre' 앞에 생김, default
padded

array([[1, 5, 0, 0, 0, 0, 0],
       [1, 6, 5, 0, 0, 0, 0],
       [1, 3, 5, 0, 0, 0, 0],
       [6, 2, 0, 0, 0, 0, 0],
       [2, 4, 3, 2, 0, 0, 0],
       [3, 2, 0, 0, 0, 0, 0],
       [1, 4, 6, 0, 0, 0, 0],
       [1, 4, 6, 0, 0, 0, 0],
       [1, 4, 2, 0, 0, 0, 0],
       [6, 6, 3, 2, 6, 1, 6],
       [1, 6, 3, 6, 0, 0, 0]], dtype=int32)

## 원 핫 인코딩

In [197]:
from konlpy.tag import Okt

okt = Okt()
tokens = okt.morphs('나는 자연어 처리를 배운다')

In [198]:
word_to_index = {word : index for index, word in enumerate(tokens)}

In [199]:
def one_hot_encoding(word, word_to_index):
    one_hot_vector = [0] * (len(word_to_index))
    index = word_to_index[word]
    one_hot_vector[index] = 1
    return one_hot_vector

In [202]:
one_hot_encoding("자연어", word_to_index)

[0, 0, 1, 0, 0, 0]

# 2.케라스(Keras)를 이용한 원핫인코딩

In [209]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.utils import to_categorical

text = "나랑 점심 먹으러 갈래 점심 메뉴는 햄버거 갈래 갈래 햄버거 최고야"

tokenizer = Tokenizer()
tokenizer.fit_on_texts([text]) # 1개 리스트 안에 넣어줘야함 ,string으로 넣으면 이상하게 나옴
tokenizer.word_index

{'갈래': 1, '점심': 2, '햄버거': 3, '나랑': 4, '먹으러': 5, '메뉴는': 6, '최고야': 7}

In [210]:
encoded = tokenizer.texts_to_sequences([text])[0]

In [211]:
encoded

[4, 2, 5, 1, 2, 6, 3, 1, 1, 3, 7]

In [214]:
one_hot = to_categorical(encoded)

In [216]:
one_hot
# 원핫인코딩은 문장에 단어가 1000개면 리스트가 1000개 생겨야함 ㅋ 너무 성능 안조음

array([[0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]], dtype=float32)

In [219]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split # 머신러닝 트레인, 테스트 데이터셋 나누기

## 1. 지도 학습(Supervised)

In [231]:
arr = np.arange(0,16).reshape(4,4)
arr.size, arr.shape

(16, (4, 4))

In [237]:
arr[:,:3]

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]])

# 한국어 전처리 패키지

In [238]:
import soynlp

ModuleNotFoundError: No module named 'soynlp'